import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)} >
        <div className="text-[#331D42] min-h-screen w-full max-w-screen-2xl mx-auto ">
          <div className="min-h-screen w-full">
          {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
